### ISSUE TITLE
apples and bananas: ocaml-freestanding vs mirage-xen

### ISSUE THREAD

**Issue by hannesm** [pqwy/ocb-stubblr#7]
I don't understand the `mirage` bit in the code: you call `pkg_config(mirage-xen)` for mirage-xen, but `pkg_config(ocaml-freestanding)` for `mirage-freestanding`.

Now: `mirage-xen` are the Xen specific Mirage bits (Env/Arg/Main/MM/Time + some bindings), whereas `ocaml-freestanding` consists of nolibc/OCaml runtime/openlibm.

The corresponding package to mirage-xen would be mirage-solo5.

The corresponding package to ocaml-freestanding would be mirage-xen-ocaml / mirage-xen-posix / mirage-xen-minios (for the openlibm bits).

IMHO it would be good to have a uniform story.  And I currently fail to see which symbols to expect when I use the mirage-xen/mirage-freestanding bits.

**Comment by pqwy** [comment]
You should [expect](https://pqwy.github.io/ocb-stubblr/doc/Ocb_stubblr.html#2_2) no symbols whatsoever: `pkg-config(mirage-xen relax cflags)`. `mirage` does the linkage. For the Mirage multi-lib targets, `stubblr` only builds `.a`s.

But a better answer is: for historic reasons. It started when @talex5 first [introduced](https://github.com/mirleft/ocaml-nocrypto/blob/3efb49216c3511bf802005199535eb5d3afac1f5/postconf.ml#L31) this schema, which is what we are doing still, and it arcs at least to [here](https://github.com/mirage/mirage-entropy/blob/4f088c1be082632ff6d544632e834b45f6645e65/myocamlbuild.ml#L30).

However, I agree. Even if it makes no difference right now, if something changes, it's maybe better not to pull in -- for example -- the stubs that Mirage uses to glue its `OS` to Xen.

So unless @talex5 has objections, I'll move it to `mirage-xen-ocaml`. This `Requires` `mirage-xen-posix`, which `Requires` `libminios-xen`, which has the actual C flags that are relevant. But I suppose it's the closes thing on Xen to OCamly conditions.

**Comment by talex5** [comment]
I'm happy for all this stuff to be cleaned up...
